// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Roffus.Repository.Context;

namespace Roffus.Repository.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190628173450_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Roffus.Domain.Categoria", b =>
                {
                    b.Property<int>("CodCategoria")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NombreCategoria");

                    b.HasKey("CodCategoria");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("Roffus.Domain.ListaMuebles", b =>
                {
                    b.Property<int>("CodLista")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CodMueble1");

                    b.Property<double>("CoordX");

                    b.Property<double>("CoordY");

                    b.Property<string>("NombreLista");

                    b.Property<double>("Rotacion");

                    b.HasKey("CodLista");

                    b.HasIndex("CodMueble1");

                    b.ToTable("ListasMuebles");
                });

            modelBuilder.Entity("Roffus.Domain.Mueble", b =>
                {
                    b.Property<int>("CodMueble")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Alto");

                    b.Property<double>("Ancho");

                    b.Property<int?>("CodSubCategoria1");

                    b.Property<int?>("CodTienda1");

                    b.Property<string>("Descripcion");

                    b.Property<string>("Icono");

                    b.Property<string>("Imagen");

                    b.Property<double>("Largo");

                    b.Property<string>("NombreMueble");

                    b.HasKey("CodMueble");

                    b.HasIndex("CodSubCategoria1");

                    b.HasIndex("CodTienda1");

                    b.ToTable("Muebles");
                });

            modelBuilder.Entity("Roffus.Domain.Paquete", b =>
                {
                    b.Property<int>("CodPaquete")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CodPlantilla1");

                    b.Property<int?>("CodUsuario1");

                    b.Property<int?>("NombreListaCodLista");

                    b.HasKey("CodPaquete");

                    b.HasIndex("CodPlantilla1");

                    b.HasIndex("CodUsuario1");

                    b.HasIndex("NombreListaCodLista");

                    b.ToTable("Paquetes");
                });

            modelBuilder.Entity("Roffus.Domain.Plantilla", b =>
                {
                    b.Property<int>("CodPlantilla")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Alto");

                    b.Property<double>("Ancho");

                    b.Property<string>("Diseño");

                    b.Property<double>("Largo");

                    b.HasKey("CodPlantilla");

                    b.ToTable("Plantillas");
                });

            modelBuilder.Entity("Roffus.Domain.SubCategoria", b =>
                {
                    b.Property<int>("CodSubCategoria")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CodCategoria");

                    b.Property<string>("NombreSubCategoria");

                    b.HasKey("CodSubCategoria");

                    b.ToTable("SubCategorias");
                });

            modelBuilder.Entity("Roffus.Domain.TiendaVirtual", b =>
                {
                    b.Property<int>("CodTienda")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Link");

                    b.Property<string>("NombreTienda");

                    b.HasKey("CodTienda");

                    b.ToTable("TiendasVirtuales");
                });

            modelBuilder.Entity("Roffus.Domain.Usuario", b =>
                {
                    b.Property<int>("CodUsuario")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Contraseña");

                    b.Property<string>("Correo");

                    b.Property<DateTime>("FNacimiento");

                    b.Property<string>("Foto");

                    b.Property<string>("NombreUsuario");

                    b.HasKey("CodUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Roffus.Domain.ListaMuebles", b =>
                {
                    b.HasOne("Roffus.Domain.Mueble", "CodMueble")
                        .WithMany()
                        .HasForeignKey("CodMueble1");
                });

            modelBuilder.Entity("Roffus.Domain.Mueble", b =>
                {
                    b.HasOne("Roffus.Domain.SubCategoria", "CodSubCategoria")
                        .WithMany()
                        .HasForeignKey("CodSubCategoria1");

                    b.HasOne("Roffus.Domain.TiendaVirtual", "CodTienda")
                        .WithMany()
                        .HasForeignKey("CodTienda1");
                });

            modelBuilder.Entity("Roffus.Domain.Paquete", b =>
                {
                    b.HasOne("Roffus.Domain.Plantilla", "CodPlantilla")
                        .WithMany()
                        .HasForeignKey("CodPlantilla1");

                    b.HasOne("Roffus.Domain.Usuario", "CodUsuario")
                        .WithMany()
                        .HasForeignKey("CodUsuario1");

                    b.HasOne("Roffus.Domain.ListaMuebles", "NombreLista")
                        .WithMany()
                        .HasForeignKey("NombreListaCodLista");
                });
#pragma warning restore 612, 618
        }
    }
}
